/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ib.view;

import com.ib.controller.BuildingNumberCombo;
import com.ib.controller.PeopleInBuilding;
import com.ib.controller.Address;
import com.ib.model.BuildingNumber;
import java.awt.Dimension;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author IB
 */
public class BuildingNumberComboBox extends javax.swing.JFrame {
 Object selectedItem;
 Address address;
    /**
     * Creates new form BuildingNumberComboBox
     */
    public BuildingNumberComboBox() {
        initComponents();
          addressLabel.setVisible(false);

        BuildingNumber buildingNumber100=new BuildingNumber("100");
        BuildingNumber buildingNumber101=new BuildingNumber("101");
        BuildingNumber buildingNumber200=new BuildingNumber("200");
        BuildingNumber buildingNumber300=new BuildingNumber("300");
        BuildingNumber buildingNumber305=new BuildingNumber("305");
        BuildingNumber buildingNumber306=new BuildingNumber("306");
        BuildingNumber buildingNumber309=new BuildingNumber("309");
        BuildingNumber buildingNumber400=new BuildingNumber("400");
        BuildingNumber buildingNumber500=new BuildingNumber("500");
       //collect all object in vector and pass in model class in one shot
        Vector buildingNumberVector=new Vector();
        
        buildingNumberVector.add(buildingNumber100);
        buildingNumberVector.add(buildingNumber101);
        buildingNumberVector.add(buildingNumber200);
        buildingNumberVector.add(buildingNumber300);
        buildingNumberVector.add(buildingNumber305);
        buildingNumberVector.add(buildingNumber306);
        buildingNumberVector.add(buildingNumber309);
        buildingNumberVector.add(buildingNumber400);
        buildingNumberVector.add(buildingNumber500);
        BuildingNumberCombo buildingNum=new BuildingNumberCombo(buildingNumberVector);
        
        //making connection betwwen view and model
        jComboBox1.setModel(buildingNum);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        personNmaeTextField = new javax.swing.JTextField();
        show = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        soldFlatTextField = new javax.swing.JTextField();
        total2bhkFlatTextField = new javax.swing.JTextField();
        total3bhkFlatTextFiled = new javax.swing.JTextField();
        remening2bTextField = new javax.swing.JTextField();
        Sold3bhkFlatTextField = new javax.swing.JTextField();
        remening3BTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list);

        show.setText("show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        jLabel1.setText("flat info");

        jLabel2.setText("2bhk");

        jLabel3.setText("3bhk");

        jLabel4.setText("total flat");

        jLabel5.setText("sold%");

        jLabel6.setText("remeaning");

        total3bhkFlatTextFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total3bhkFlatTextFiledActionPerformed(evt);
            }
        });

        jButton1.setText("Click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addressLabel.setBackground(new java.awt.Color(255, 204, 102));
        addressLabel.setForeground(new java.awt.Color(255, 0, 102));

        jLabel7.setBackground(new java.awt.Color(255, 204, 51));
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Building Number");

        jLabel8.setBackground(new java.awt.Color(255, 204, 102));
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("People In Building");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personNmaeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(show))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(40, 40, 40)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(40, 40, 40)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total2bhkFlatTextField)
                                    .addComponent(total3bhkFlatTextFiled))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Sold3bhkFlatTextField)
                                        .addGap(32, 32, 32)
                                        .addComponent(remening3BTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(38, 38, 38))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(soldFlatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(25, 25, 25))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(remening2bTextField)
                                                .addContainerGap())))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(81, 81, 81))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(total2bhkFlatTextField)
                            .addComponent(soldFlatTextField)
                            .addComponent(remening2bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(total3bhkFlatTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(remening3BTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Sold3bhkFlatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(personNmaeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(show)))
                .addGap(31, 31, 31)
                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        selectedItem = jComboBox1.getSelectedItem();
        PeopleInBuilding.peopleName((BuildingNumber) selectedItem,list);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
 address=new Address(personNmaeTextField);
        String name=personNmaeTextField.getText();
if(name.equals("govind mantri")&&selectedItem.toString().equals("100"))
{
   addressLabel.setText("Name- :"+"---- : "+name+"----"+"building Number= :"+selectedItem+"--"+"flat number :"+address.flatNumber()+"flat type :"+address.flatType()+"---->"+address.OwnerOrTenants());
 
   addressLabel.setVisible(true);
}
if(name.equals("namdeo")&&selectedItem.toString().equals("101"))
{
    addressLabel.setText("");
    System.out.println(address.flatType());
   addressLabel.setText("Name- :"+"---- : "+name+"----"+"building Number= :"+selectedItem+"--"+"flat number :"+address.flatNumber()+"flat type :"+address.flatType()+"---->"+address.OwnerOrTenants());
   addressLabel.setVisible(true);
}
       
    
    }//GEN-LAST:event_showActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
     Object selectedValue = list.getSelectedValue();
        System.out.println(selectedValue);
        personNmaeTextField.setText(selectedValue.toString());
    }//GEN-LAST:event_listMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Object selectedItem1 = jComboBox1.getSelectedItem();
     if(selectedItem1.toString().equals("100"))
     {
         
         total2bhkFlatTextField.setText("10");
         total3bhkFlatTextFiled.setText("5");
        float sold2bhk= list.getModel().getSize();
         soldFlatTextField.setText(sold2bhk+"");
          String twob= total2bhkFlatTextField.getText();
      
       
       int total=Integer.parseInt(twob);
       float avgSold=(float)(sold2bhk/total)*100;
        
         System.out.println(sold2bhk);
         System.out.println(avgSold);
        Sold3bhkFlatTextField.setText(avgSold+"");
         soldFlatTextField.setText(avgSold+"");
          float remeningFlat=100-avgSold;
         remening2bTextField.setText(""+remeningFlat);
         remening3BTextField.setText(""+remeningFlat);
         
     } if(selectedItem1.toString().equals("101"))
     {
         total2bhkFlatTextField.setText("15");
         total3bhkFlatTextFiled.setText("7");
        float sold3bhk= list.getModel().getSize();
       String twob= total2bhkFlatTextField.getText();
       int total=Integer.parseInt(twob);
       float avgSold=(float)(sold3bhk/total)*100;
        
         System.out.println(sold3bhk);
         System.out.println(avgSold);
        Sold3bhkFlatTextField.setText(avgSold+"");
         soldFlatTextField.setText(avgSold+"");
         float remeningFlat=100-avgSold;
         remening2bTextField.setText(""+remeningFlat);
         remening3BTextField.setText(""+remeningFlat);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void total3bhkFlatTextFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total3bhkFlatTextFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total3bhkFlatTextFiledActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildingNumberComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildingNumberComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildingNumberComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildingNumberComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Sold3bhkFlatTextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    private javax.swing.JTextField personNmaeTextField;
    private javax.swing.JTextField remening2bTextField;
    private javax.swing.JTextField remening3BTextField;
    private javax.swing.JButton show;
    private javax.swing.JTextField soldFlatTextField;
    private javax.swing.JTextField total2bhkFlatTextField;
    private javax.swing.JTextField total3bhkFlatTextFiled;
    // End of variables declaration//GEN-END:variables
}
